server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb  # JDBC URL for H2 in-memory database
    driver-class-name: org.h2.Driver  # H2 database driver class name
    username: sa  # H2 database username
    password: password  # H2 database password
  h2:
    console:
      enabled: true  # Enable H2 console
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema based on the entities

#    pa:
#       database-platform: org.hibernate.dialect.H2Dialect
#       hibernate:
#           ddl-auto: update
  application:
          name: ORDER-SERVICE
  config:
    import:configserver: http://localhost:9296
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://eureka-server-host:8761/eureka/


  